coins = 0
price = round(float(input()), 2)
while price != 0:
    if price >= 2:
        price -= 2
        coins += 1
    elif price >= 1:
        price -= 1
        coins += 1
    elif price >= 0.50:
        price -= 0.50
        coins += 1
    elif price >= 0.20:
        price -= 0.20
        coins += 1
    elif price >= 0.10:
        price -= 0.10
        coins += 1
    elif price >= 0.05:
        price -= 0.05
        coins += 1
    elif price >= 0.02:
        price -= 0.02
        coins += 1
    elif price >= 0.01:
        price -= 0.01
        coins += 1
    price = round(price, 2)
print (coins)